#!/usr/bin/env python3
import cv2, numpy as np, glob, camera_configs as old
board = (9,6)        # 内角点
square = 25          # mm
imgs_l = sorted(glob.glob('left/*.png'))
imgs_r = sorted(glob.glob('right/*.png'))

# 找角点
objp = np.zeros((board[0]*board[1],3), np.float32)
objp[:,:2] = np.mgrid[0:board[0],0:board[1]].T.reshape(-1,2)*square
objpts, imgpts_l, imgpts_r = [], [], []

for l,r in zip(imgs_l, imgs_r):
    im_l, im_r = cv2.imread(l), cv2.imread(r)
    gray_l = cv2.cvtColor(im_l, cv2.COLOR_BGR2GRAY)
    gray_r = cv2.cvtColor(im_r, cv2.COLOR_BGR2GRAY)
    ret_l, corners_l = cv2.findChessboardCorners(gray_l, board, None)
    ret_r, corners_r = cv2.findChessboardCorners(gray_r, board, None)
    if ret_l and ret_r:
        objpts.append(objp)
        cv2.cornerSubPix(gray_l, corners_l, (11,11), (-1,-1),
                         (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,30,0.001))
        cv2.cornerSubPix(gray_r, corners_r, (11,11), (-1,-1),
                         (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,30,0.001))
        imgpts_l.append(corners_l); imgpts_r.append(corners_r)

# 标定
K1, D1, _, _ = cv2.calibrateCamera(objpts, imgpts_l, gray_l.shape[::-1], None, None)
K2, D2, _, _ = cv2.calibrateCamera(objpts, imgpts_r, gray_r.shape[::-1], None, None)

# 立体标定
flags = cv2.CALIB_FIX_INTRINSIC
ret, K1, D1, K2, D2, R, T, E, F = cv2.stereoCalibrate(
        objpts, imgpts_l, imgpts_r, K1, D1, K2, D2,
        gray_l.shape[::-1], flags=flags,
        criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6))

# 生成新的 camera_configs.py
with open('camera_configs.py','w') as f:
    f.write(f'''# auto-generated by calib_stereo.py
import numpy as np, cv2
K1 = np.{repr(K1)}
D1 = np.{repr(D1)}
K2 = np.{repr(K2)}
D2 = np.{repr(D2)}
R  = np.{repr(R)}
T  = np.{repr(T)}
img_size = {gray_l.shape[::-1]}
R1,R2,P1,P2,Q,_,_ = cv2.stereoRectify(K1,D1,K2,D2,img_size,R,T)
left_map1,left_map2 = cv2.initUndistortRectifyMap(K1,D1,R1,P1,img_size,cv2.CV_16SC2)
right_map1,right_map2 = cv2.initUndistortRectifyMap(K2,D2,R2,P2,img_size,cv2.CV_16SC2)
''')
print('新 camera_configs.py 已生成，Q=\n', np.array2string(P2,corner_mask))